# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kutuphane.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 780))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 780))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/beulogo_login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1250, 780))
        self.centralwidget.setMaximumSize(QtCore.QSize(1250, 780))
        self.centralwidget.setStyleSheet("background:url(:/images/images/martin-adams-_OZCl4XcpRw-unsplash (1).jpg);\n"
"\n"
"QPushButton{\n"
"color:green;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1250, 780))
        self.frame.setMinimumSize(QtCore.QSize(1250, 780))
        self.frame.setMaximumSize(QtCore.QSize(1250, 780))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame{\n"
"background:rgba(53, 63, 89,0.9);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_profil = QtWidgets.QPushButton(self.frame)
        self.btn_profil.setGeometry(QtCore.QRect(0, 100, 175, 170))
        self.btn_profil.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_profil.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_profil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_profil.setStyleSheet("QPushButton{\n"
"background:rgba(101,52,172,0.93);border:none;color:white;font-size:28px;\n"
"}\n"
"")
        self.btn_profil.setObjectName("btn_profil")
        self.gorevCubugu = QtWidgets.QFrame(self.frame)
        self.gorevCubugu.setGeometry(QtCore.QRect(0, 40, 1250, 60))
        self.gorevCubugu.setStyleSheet("QFrame{\n"
"background-color:rgba(25,35,49,0.699);\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.gorevCubugu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gorevCubugu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gorevCubugu.setObjectName("gorevCubugu")
        self.label_telefon_no = QtWidgets.QLabel(self.gorevCubugu)
        self.label_telefon_no.setGeometry(QtCore.QRect(12, 32, 391, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.label_telefon_no.setFont(font)
        self.label_telefon_no.setStyleSheet("color:silver;\n"
"background:transparent;\n"
"border:none;")
        self.label_telefon_no.setObjectName("label_telefon_no")
        self.label_username = QtWidgets.QLabel(self.gorevCubugu)
        self.label_username.setGeometry(QtCore.QRect(12, 3, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("color:silver;\n"
"background:transparent;\n"
"border:none;")
        self.label_username.setObjectName("label_username")
        self.btn_kitap = QtWidgets.QPushButton(self.frame)
        self.btn_kitap.setGeometry(QtCore.QRect(0, 270, 175, 170))
        self.btn_kitap.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kitap.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kitap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitap.setStyleSheet("\n"
"QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(40,49,71,0.97);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}")
        self.btn_kitap.setObjectName("btn_kitap")
        self.btn_odunc = QtWidgets.QPushButton(self.frame)
        self.btn_odunc.setGeometry(QtCore.QRect(0, 440, 175, 170))
        self.btn_odunc.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_odunc.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_odunc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_odunc.setStyleSheet("\n"
"QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(40,49,71,0.97);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}")
        self.btn_odunc.setObjectName("btn_odunc")
        self.btn_kullanici = QtWidgets.QPushButton(self.frame)
        self.btn_kullanici.setGeometry(QtCore.QRect(0, 610, 175, 170))
        self.btn_kullanici.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kullanici.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kullanici.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullanici.setStyleSheet("\n"
"QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(40,49,71,0.97);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}")
        self.btn_kullanici.setObjectName("btn_kullanici")
        self.mainStack = QtWidgets.QStackedWidget(self.frame)
        self.mainStack.setGeometry(QtCore.QRect(175, 100, 1075, 700))
        self.mainStack.setStyleSheet("QWidget{\n"
"background:rgba(0,0,0,0.0001)\n"
"}")
        self.mainStack.setObjectName("mainStack")
        self.qw_profil = QtWidgets.QWidget()
        self.qw_profil.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.97);\n"
"border:none;\n"
"color:white;\n"
"}\n"
"\n"
"QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QTextEdit{\n"
"font-size:24px;;\n"
"color:white;\n"
"border:none;\n"
"border-radius:7px;\n"
"background:rgba(0,0,0,0.11);\n"
"}\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.qw_profil.setObjectName("qw_profil")
        self.profil_ad = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_ad.setEnabled(False)
        self.profil_ad.setGeometry(QtCore.QRect(50, 70, 448, 41))
        self.profil_ad.setText("")
        self.profil_ad.setMaxLength(24)
        self.profil_ad.setFrame(True)
        self.profil_ad.setObjectName("profil_ad")
        self.profil_mail = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_mail.setEnabled(False)
        self.profil_mail.setGeometry(QtCore.QRect(50, 230, 448, 41))
        self.profil_mail.setText("")
        self.profil_mail.setMaxLength(24)
        self.profil_mail.setObjectName("profil_mail")
        self.profil_kullanici_adi = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_kullanici_adi.setEnabled(False)
        self.profil_kullanici_adi.setGeometry(QtCore.QRect(50, 150, 448, 41))
        self.profil_kullanici_adi.setText("")
        self.profil_kullanici_adi.setMaxLength(24)
        self.profil_kullanici_adi.setObjectName("profil_kullanici_adi")
        self.profil_telefon = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_telefon.setEnabled(False)
        self.profil_telefon.setGeometry(QtCore.QRect(540, 230, 448, 41))
        self.profil_telefon.setText("")
        self.profil_telefon.setMaxLength(24)
        self.profil_telefon.setObjectName("profil_telefon")
        self.profil_parola = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_parola.setEnabled(False)
        self.profil_parola.setGeometry(QtCore.QRect(540, 150, 448, 41))
        self.profil_parola.setText("")
        self.profil_parola.setMaxLength(24)
        self.profil_parola.setObjectName("profil_parola")
        self.profil_soyad = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_soyad.setEnabled(False)
        self.profil_soyad.setGeometry(QtCore.QRect(540, 70, 448, 41))
        self.profil_soyad.setText("")
        self.profil_soyad.setMaxLength(24)
        self.profil_soyad.setFrame(True)
        self.profil_soyad.setObjectName("profil_soyad")
        self.profil_parola_yeni = QtWidgets.QLineEdit(self.qw_profil)
        self.profil_parola_yeni.setGeometry(QtCore.QRect(50, 400, 448, 41))
        self.profil_parola_yeni.setText("")
        self.profil_parola_yeni.setMaxLength(24)
        self.profil_parola_yeni.setObjectName("profil_parola_yeni")
        self.btn_profilParola = QtWidgets.QPushButton(self.qw_profil)
        self.btn_profilParola.setGeometry(QtCore.QRect(540, 390, 447, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_profilParola.setFont(font)
        self.btn_profilParola.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_profilParola.setObjectName("btn_profilParola")
        self.label_26 = QtWidgets.QLabel(self.qw_profil)
        self.label_26.setGeometry(QtCore.QRect(80, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.label_22 = QtWidgets.QLabel(self.qw_profil)
        self.label_22.setGeometry(QtCore.QRect(50, 12, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.qw_profil)
        self.label_23.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.mainStack.addWidget(self.qw_profil)
        self.qw_kitap = QtWidgets.QWidget()
        self.qw_kitap.setObjectName("qw_kitap")
        self.kitapStack = QtWidgets.QStackedWidget(self.qw_kitap)
        self.kitapStack.setGeometry(QtCore.QRect(0, 0, 1075, 700))
        self.kitapStack.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.97);\n"
"border:none;\n"
"color:white;\n"
"}\n"
"\n"
"QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QTextEdit{\n"
"font-size:24px;;\n"
"color:white;\n"
"border:none;\n"
"border-radius:7px;\n"
"background:rgba(0,0,0,0.11);\n"
"}\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.kitapStack.setObjectName("kitapStack")
        self.qw_kitap_ekle = QtWidgets.QWidget()
        self.qw_kitap_ekle.setStyleSheet("")
        self.qw_kitap_ekle.setObjectName("qw_kitap_ekle")
        self.label_18 = QtWidgets.QLabel(self.qw_kitap_ekle)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.qw_kitap_ekle)
        self.label_19.setGeometry(QtCore.QRect(93, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.qw_kitap_ekle)
        self.label_24.setGeometry(QtCore.QRect(128, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.frame_5 = QtWidgets.QFrame(self.qw_kitap_ekle)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1091, 691))
        self.frame_5.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QTextEdit{\n"
"font-size:24px;;\n"
"color:white;\n"
"border:none;\n"
"border-radius:7px;\n"
"background:rgba(0,0,0,0.11);\n"
"}\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.kitap_ekle_yazar = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_yazar.setGeometry(QtCore.QRect(50, 250, 448, 41))
        self.kitap_ekle_yazar.setText("")
        self.kitap_ekle_yazar.setMaxLength(24)
        self.kitap_ekle_yazar.setObjectName("kitap_ekle_yazar")
        self.kitap_ekle_adi = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_adi.setGeometry(QtCore.QRect(50, 190, 448, 41))
        self.kitap_ekle_adi.setText("")
        self.kitap_ekle_adi.setMaxLength(24)
        self.kitap_ekle_adi.setFrame(True)
        self.kitap_ekle_adi.setObjectName("kitap_ekle_adi")
        self.btn_kitapEkle = QtWidgets.QPushButton(self.frame_5)
        self.btn_kitapEkle.setGeometry(QtCore.QRect(40, 520, 447, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapEkle.setFont(font)
        self.btn_kitapEkle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapEkle.setObjectName("btn_kitapEkle")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(51, 70, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_11.setObjectName("label_11")
        self.label_33 = QtWidgets.QLabel(self.frame_5)
        self.label_33.setGeometry(QtCore.QRect(56, 124, 411, 41))
        self.label_33.setStyleSheet("background:transparent;\n"
"color:silver;\n"
"border:none;\n"
"font-size:15px;")
        self.label_33.setObjectName("label_33")
        self.kitap_ekle_sayfa = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_sayfa.setGeometry(QtCore.QRect(50, 440, 209, 41))
        self.kitap_ekle_sayfa.setText("")
        self.kitap_ekle_sayfa.setMaxLength(24)
        self.kitap_ekle_sayfa.setObjectName("kitap_ekle_sayfa")
        self.kitap_ekle_basim = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_basim.setGeometry(QtCore.QRect(290, 440, 209, 41))
        self.kitap_ekle_basim.setText("")
        self.kitap_ekle_basim.setMaxLength(24)
        self.kitap_ekle_basim.setObjectName("kitap_ekle_basim")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(580, 80, 441, 401))
        self.frame_6.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.6);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_40 = QtWidgets.QLabel(self.frame_6)
        self.label_40.setGeometry(QtCore.QRect(100, 130, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(35)
        font.setUnderline(False)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:white;\n"
"background:transparent;")
        self.label_40.setObjectName("label_40")
        self.kitap_ekle_yayinevi = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_yayinevi.setGeometry(QtCore.QRect(50, 310, 448, 41))
        self.kitap_ekle_yayinevi.setText("")
        self.kitap_ekle_yayinevi.setMaxLength(24)
        self.kitap_ekle_yayinevi.setObjectName("kitap_ekle_yayinevi")
        self.kitap_ekle_tur = QtWidgets.QLineEdit(self.frame_5)
        self.kitap_ekle_tur.setGeometry(QtCore.QRect(50, 370, 448, 41))
        self.kitap_ekle_tur.setText("")
        self.kitap_ekle_tur.setMaxLength(24)
        self.kitap_ekle_tur.setObjectName("kitap_ekle_tur")
        self.kitapStack.addWidget(self.qw_kitap_ekle)
        self.qw_kitap_duzenle = QtWidgets.QWidget()
        self.qw_kitap_duzenle.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QTextEdit{\n"
"font-size:24px;;\n"
"color:white;\n"
"border:none;\n"
"border-radius:7px;\n"
"background:rgba(0,0,0,0.11);\n"
"}\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.qw_kitap_duzenle.setObjectName("qw_kitap_duzenle")
        self.label_20 = QtWidgets.QLabel(self.qw_kitap_duzenle)
        self.label_20.setGeometry(QtCore.QRect(93, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.qw_kitap_duzenle)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.qw_kitap_duzenle)
        self.label_25.setGeometry(QtCore.QRect(128, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.kitap_edit_ad = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_ad.setEnabled(True)
        self.kitap_edit_ad.setGeometry(QtCore.QRect(69, 292, 461, 61))
        self.kitap_edit_ad.setText("")
        self.kitap_edit_ad.setMaxLength(24)
        self.kitap_edit_ad.setObjectName("kitap_edit_ad")
        self.kitap_edit_sayfa = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_sayfa.setGeometry(QtCore.QRect(69, 452, 461, 61))
        self.kitap_edit_sayfa.setText("")
        self.kitap_edit_sayfa.setMaxLength(40)
        self.kitap_edit_sayfa.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.kitap_edit_sayfa.setObjectName("kitap_edit_sayfa")
        self.label_9 = QtWidgets.QLabel(self.qw_kitap_duzenle)
        self.label_9.setGeometry(QtCore.QRect(79, 106, 691, 61))
        self.label_9.setStyleSheet("background:transparent;\n"
"color:silver;\n"
"border:none;\n"
"font-size:15px;")
        self.label_9.setObjectName("label_9")
        self.kitap_edit_yayinevi = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_yayinevi.setGeometry(QtCore.QRect(69, 372, 461, 61))
        self.kitap_edit_yayinevi.setText("")
        self.kitap_edit_yayinevi.setMaxLength(24)
        self.kitap_edit_yayinevi.setObjectName("kitap_edit_yayinevi")
        self.kitap_edit_basim = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_basim.setGeometry(QtCore.QRect(586, 452, 461, 61))
        self.kitap_edit_basim.setText("")
        self.kitap_edit_basim.setMaxLength(40)
        self.kitap_edit_basim.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.kitap_edit_basim.setObjectName("kitap_edit_basim")
        self.btn_kitapSil = QtWidgets.QPushButton(self.qw_kitap_duzenle)
        self.btn_kitapSil.setGeometry(QtCore.QRect(587, 543, 225, 64))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapSil.setFont(font)
        self.btn_kitapSil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapSil.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(255, 66, 69)\n"
"}")
        self.btn_kitapSil.setObjectName("btn_kitapSil")
        self.kitap_edit_tur = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_tur.setGeometry(QtCore.QRect(586, 372, 461, 61))
        self.kitap_edit_tur.setText("")
        self.kitap_edit_tur.setMaxLength(40)
        self.kitap_edit_tur.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.kitap_edit_tur.setObjectName("kitap_edit_tur")
        self.btn_kitapDuzenle = QtWidgets.QPushButton(self.qw_kitap_duzenle)
        self.btn_kitapDuzenle.setGeometry(QtCore.QRect(829, 543, 225, 64))
        self.btn_kitapDuzenle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapDuzenle.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_kitapDuzenle.setObjectName("btn_kitapDuzenle")
        self.btn_kitapBilgileriGetir = QtWidgets.QPushButton(self.qw_kitap_duzenle)
        self.btn_kitapBilgileriGetir.setGeometry(QtCore.QRect(380, 210, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapBilgileriGetir.setFont(font)
        self.btn_kitapBilgileriGetir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapBilgileriGetir.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_kitapBilgileriGetir.setObjectName("btn_kitapBilgileriGetir")
        self.label_12 = QtWidgets.QLabel(self.qw_kitap_duzenle)
        self.label_12.setGeometry(QtCore.QRect(74, 52, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_12.setObjectName("label_12")
        self.kitap_edit_yazar = QtWidgets.QLineEdit(self.qw_kitap_duzenle)
        self.kitap_edit_yazar.setGeometry(QtCore.QRect(586, 292, 461, 61))
        self.kitap_edit_yazar.setText("")
        self.kitap_edit_yazar.setMaxLength(24)
        self.kitap_edit_yazar.setFrame(True)
        self.kitap_edit_yazar.setObjectName("kitap_edit_yazar")
        self.combo_edit_kitap = QtWidgets.QComboBox(self.qw_kitap_duzenle)
        self.combo_edit_kitap.setEnabled(True)
        self.combo_edit_kitap.setGeometry(QtCore.QRect(80, 210, 271, 23))
        self.combo_edit_kitap.setAutoFillBackground(False)
        self.combo_edit_kitap.setStyleSheet("\n"
"font-size:15px;\n"
"color:rgb(195, 195, 195);\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"")
        self.combo_edit_kitap.setEditable(False)
        self.combo_edit_kitap.setCurrentText("")
        self.combo_edit_kitap.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_edit_kitap.setDuplicatesEnabled(False)
        self.combo_edit_kitap.setFrame(True)
        self.combo_edit_kitap.setModelColumn(0)
        self.combo_edit_kitap.setObjectName("combo_edit_kitap")
        self.kitapStack.addWidget(self.qw_kitap_duzenle)
        self.qw_kitap_test = QtWidgets.QWidget()
        self.qw_kitap_test.setStyleSheet("QTableWidget{\n"
"background:transparent;\n"
"color:white;\n"
"}")
        self.qw_kitap_test.setObjectName("qw_kitap_test")
        self.tableWidget = QtWidgets.QTableWidget(self.qw_kitap_test)
        self.tableWidget.setGeometry(QtCore.QRect(180, 10, 731, 461))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.btn_kullaniciAra_2 = QtWidgets.QPushButton(self.qw_kitap_test)
        self.btn_kullaniciAra_2.setGeometry(QtCore.QRect(650, 510, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kullaniciAra_2.setFont(font)
        self.btn_kullaniciAra_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullaniciAra_2.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_kullaniciAra_2.setObjectName("btn_kullaniciAra_2")
        self.kullanici_ogr_no_3 = QtWidgets.QLineEdit(self.qw_kitap_test)
        self.kullanici_ogr_no_3.setGeometry(QtCore.QRect(290, 520, 311, 41))
        self.kullanici_ogr_no_3.setText("")
        self.kullanici_ogr_no_3.setMaxLength(24)
        self.kullanici_ogr_no_3.setFrame(True)
        self.kullanici_ogr_no_3.setObjectName("kullanici_ogr_no_3")
        self.btn_kitapBilgileriGetir_2 = QtWidgets.QPushButton(self.qw_kitap_test)
        self.btn_kitapBilgileriGetir_2.setGeometry(QtCore.QRect(920, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapBilgileriGetir_2.setFont(font)
        self.btn_kitapBilgileriGetir_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapBilgileriGetir_2.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_kitapBilgileriGetir_2.setObjectName("btn_kitapBilgileriGetir_2")
        self.kitapStack.addWidget(self.qw_kitap_test)
        self.mainStack.addWidget(self.qw_kitap)
        self.qw_odunc = QtWidgets.QWidget()
        self.qw_odunc.setObjectName("qw_odunc")
        self.oduncStack = QtWidgets.QStackedWidget(self.qw_odunc)
        self.oduncStack.setGeometry(QtCore.QRect(0, 0, 1075, 700))
        self.oduncStack.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.93);\n"
"border:none;\n"
"color:silver;\n"
"font-size:28px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.97);\n"
"border:none;\n"
"color:white;\n"
"}")
        self.oduncStack.setObjectName("oduncStack")
        self.qw_odunc_ver = QtWidgets.QWidget()
        self.qw_odunc_ver.setObjectName("qw_odunc_ver")
        self.label_4 = QtWidgets.QLabel(self.qw_odunc_ver)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.qw_odunc_ver)
        self.label_10.setGeometry(QtCore.QRect(100, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.qw_odunc_ver)
        self.label_15.setGeometry(QtCore.QRect(128, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.frame_3 = QtWidgets.QFrame(self.qw_odunc_ver)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1091, 691))
        self.frame_3.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.04);\n"
"}\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(68, 117, 222)\n"
"}\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_oduncVer = QtWidgets.QPushButton(self.frame_3)
        self.btn_oduncVer.setGeometry(QtCore.QRect(300, 590, 470, 64))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_oduncVer.setFont(font)
        self.btn_oduncVer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_oduncVer.setObjectName("btn_oduncVer")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(290, 10, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.combo_odunc_kitap = QtWidgets.QComboBox(self.frame_3)
        self.combo_odunc_kitap.setEnabled(True)
        self.combo_odunc_kitap.setGeometry(QtCore.QRect(50, 140, 271, 23))
        self.combo_odunc_kitap.setAutoFillBackground(False)
        self.combo_odunc_kitap.setStyleSheet("\n"
"font-size:15px;\n"
"color:rgb(195, 195, 195);\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"")
        self.combo_odunc_kitap.setEditable(False)
        self.combo_odunc_kitap.setCurrentText("")
        self.combo_odunc_kitap.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_odunc_kitap.setDuplicatesEnabled(False)
        self.combo_odunc_kitap.setFrame(True)
        self.combo_odunc_kitap.setModelColumn(0)
        self.combo_odunc_kitap.setObjectName("combo_odunc_kitap")
        self.odunc_ver_barkod = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_barkod.setEnabled(True)
        self.odunc_ver_barkod.setGeometry(QtCore.QRect(40, 200, 461, 61))
        self.odunc_ver_barkod.setText("")
        self.odunc_ver_barkod.setMaxLength(24)
        self.odunc_ver_barkod.setObjectName("odunc_ver_barkod")
        self.btn_kitapBilgileriGetir_3 = QtWidgets.QPushButton(self.frame_3)
        self.btn_kitapBilgileriGetir_3.setGeometry(QtCore.QRect(350, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapBilgileriGetir_3.setFont(font)
        self.btn_kitapBilgileriGetir_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapBilgileriGetir_3.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_kitapBilgileriGetir_3.setObjectName("btn_kitapBilgileriGetir_3")
        self.odunc_ver_kitap = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_kitap.setEnabled(True)
        self.odunc_ver_kitap.setGeometry(QtCore.QRect(40, 290, 461, 61))
        self.odunc_ver_kitap.setText("")
        self.odunc_ver_kitap.setMaxLength(24)
        self.odunc_ver_kitap.setObjectName("odunc_ver_kitap")
        self.odunc_ver_yazar = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_yazar.setEnabled(True)
        self.odunc_ver_yazar.setGeometry(QtCore.QRect(40, 380, 461, 61))
        self.odunc_ver_yazar.setText("")
        self.odunc_ver_yazar.setMaxLength(24)
        self.odunc_ver_yazar.setObjectName("odunc_ver_yazar")
        self.combo_odunc_kullanici = QtWidgets.QComboBox(self.frame_3)
        self.combo_odunc_kullanici.setEnabled(True)
        self.combo_odunc_kullanici.setGeometry(QtCore.QRect(570, 140, 271, 23))
        self.combo_odunc_kullanici.setAutoFillBackground(False)
        self.combo_odunc_kullanici.setStyleSheet("\n"
"font-size:15px;\n"
"color:rgb(195, 195, 195);\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"")
        self.combo_odunc_kullanici.setEditable(False)
        self.combo_odunc_kullanici.setCurrentText("")
        self.combo_odunc_kullanici.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_odunc_kullanici.setDuplicatesEnabled(False)
        self.combo_odunc_kullanici.setFrame(True)
        self.combo_odunc_kullanici.setModelColumn(0)
        self.combo_odunc_kullanici.setObjectName("combo_odunc_kullanici")
        self.btn_kitapBilgileriGetir_4 = QtWidgets.QPushButton(self.frame_3)
        self.btn_kitapBilgileriGetir_4.setGeometry(QtCore.QRect(860, 140, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kitapBilgileriGetir_4.setFont(font)
        self.btn_kitapBilgileriGetir_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitapBilgileriGetir_4.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_kitapBilgileriGetir_4.setObjectName("btn_kitapBilgileriGetir_4")
        self.odunc_ver_adsoyad = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_adsoyad.setEnabled(True)
        self.odunc_ver_adsoyad.setGeometry(QtCore.QRect(570, 290, 461, 61))
        self.odunc_ver_adsoyad.setText("")
        self.odunc_ver_adsoyad.setMaxLength(24)
        self.odunc_ver_adsoyad.setObjectName("odunc_ver_adsoyad")
        self.odunc_ver_ogrno = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_ogrno.setEnabled(True)
        self.odunc_ver_ogrno.setGeometry(QtCore.QRect(570, 200, 461, 61))
        self.odunc_ver_ogrno.setText("")
        self.odunc_ver_ogrno.setMaxLength(24)
        self.odunc_ver_ogrno.setObjectName("odunc_ver_ogrno")
        self.odunc_ver_telefon = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_telefon.setEnabled(True)
        self.odunc_ver_telefon.setGeometry(QtCore.QRect(570, 380, 461, 61))
        self.odunc_ver_telefon.setText("")
        self.odunc_ver_telefon.setMaxLength(24)
        self.odunc_ver_telefon.setObjectName("odunc_ver_telefon")
        self.odunc_ver_yayinevi = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_yayinevi.setEnabled(True)
        self.odunc_ver_yayinevi.setGeometry(QtCore.QRect(40, 470, 461, 61))
        self.odunc_ver_yayinevi.setText("")
        self.odunc_ver_yayinevi.setMaxLength(24)
        self.odunc_ver_yayinevi.setObjectName("odunc_ver_yayinevi")
        self.odunc_ver_tarih = QtWidgets.QLineEdit(self.frame_3)
        self.odunc_ver_tarih.setEnabled(True)
        self.odunc_ver_tarih.setGeometry(QtCore.QRect(570, 470, 461, 61))
        self.odunc_ver_tarih.setText("")
        self.odunc_ver_tarih.setMaxLength(24)
        self.odunc_ver_tarih.setObjectName("odunc_ver_tarih")
        self.label_15.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.frame_3.raise_()
        self.oduncStack.addWidget(self.qw_odunc_ver)
        self.qw_odunc_iade = QtWidgets.QWidget()
        self.qw_odunc_iade.setObjectName("qw_odunc_iade")
        self.label_13 = QtWidgets.QLabel(self.qw_odunc_iade)
        self.label_13.setGeometry(QtCore.QRect(100, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.qw_odunc_iade)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.qw_odunc_iade)
        self.label_16.setGeometry(QtCore.QRect(128, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.frame_4 = QtWidgets.QFrame(self.qw_odunc_iade)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1075, 700))
        self.frame_4.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"QTextEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_oduncIade = QtWidgets.QPushButton(self.frame_4)
        self.btn_oduncIade.setGeometry(QtCore.QRect(410, 570, 225, 64))
        self.btn_oduncIade.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_oduncIade.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_oduncIade.setObjectName("btn_oduncIade")
        self.odunc_iade_yazar = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_yazar.setEnabled(True)
        self.odunc_iade_yazar.setGeometry(QtCore.QRect(30, 380, 461, 61))
        self.odunc_iade_yazar.setText("")
        self.odunc_iade_yazar.setMaxLength(24)
        self.odunc_iade_yazar.setObjectName("odunc_iade_yazar")
        self.odunc_iade_telefon = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_telefon.setEnabled(True)
        self.odunc_iade_telefon.setGeometry(QtCore.QRect(560, 380, 461, 61))
        self.odunc_iade_telefon.setText("")
        self.odunc_iade_telefon.setMaxLength(24)
        self.odunc_iade_telefon.setObjectName("odunc_iade_telefon")
        self.odunc_iade_tarih = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_tarih.setEnabled(True)
        self.odunc_iade_tarih.setGeometry(QtCore.QRect(560, 470, 461, 61))
        self.odunc_iade_tarih.setText("")
        self.odunc_iade_tarih.setMaxLength(24)
        self.odunc_iade_tarih.setObjectName("odunc_iade_tarih")
        self.combo_odunc_bilgi = QtWidgets.QComboBox(self.frame_4)
        self.combo_odunc_bilgi.setEnabled(True)
        self.combo_odunc_bilgi.setGeometry(QtCore.QRect(40, 140, 451, 23))
        self.combo_odunc_bilgi.setAutoFillBackground(False)
        self.combo_odunc_bilgi.setStyleSheet("\n"
"font-size:15px;\n"
"color:rgb(195, 195, 195);\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"")
        self.combo_odunc_bilgi.setEditable(False)
        self.combo_odunc_bilgi.setCurrentText("")
        self.combo_odunc_bilgi.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_odunc_bilgi.setDuplicatesEnabled(False)
        self.combo_odunc_bilgi.setFrame(True)
        self.combo_odunc_bilgi.setModelColumn(0)
        self.combo_odunc_bilgi.setObjectName("combo_odunc_bilgi")
        self.odunc_iade_barkod = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_barkod.setEnabled(True)
        self.odunc_iade_barkod.setGeometry(QtCore.QRect(30, 200, 461, 61))
        self.odunc_iade_barkod.setText("")
        self.odunc_iade_barkod.setMaxLength(24)
        self.odunc_iade_barkod.setObjectName("odunc_iade_barkod")
        self.odunc_iade_ogrno = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_ogrno.setEnabled(True)
        self.odunc_iade_ogrno.setGeometry(QtCore.QRect(560, 200, 461, 61))
        self.odunc_iade_ogrno.setText("")
        self.odunc_iade_ogrno.setMaxLength(24)
        self.odunc_iade_ogrno.setObjectName("odunc_iade_ogrno")
        self.odunc_iade_adsoyad = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_adsoyad.setEnabled(True)
        self.odunc_iade_adsoyad.setGeometry(QtCore.QRect(560, 290, 461, 61))
        self.odunc_iade_adsoyad.setText("")
        self.odunc_iade_adsoyad.setMaxLength(24)
        self.odunc_iade_adsoyad.setObjectName("odunc_iade_adsoyad")
        self.odunc_iade_yayinevi = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_yayinevi.setEnabled(True)
        self.odunc_iade_yayinevi.setGeometry(QtCore.QRect(30, 470, 461, 61))
        self.odunc_iade_yayinevi.setText("")
        self.odunc_iade_yayinevi.setMaxLength(24)
        self.odunc_iade_yayinevi.setObjectName("odunc_iade_yayinevi")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(280, 10, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.odunc_iade_kitap = QtWidgets.QLineEdit(self.frame_4)
        self.odunc_iade_kitap.setEnabled(True)
        self.odunc_iade_kitap.setGeometry(QtCore.QRect(30, 290, 461, 61))
        self.odunc_iade_kitap.setText("")
        self.odunc_iade_kitap.setMaxLength(24)
        self.odunc_iade_kitap.setObjectName("odunc_iade_kitap")
        self.btn_oduncBilgileriGetir_5 = QtWidgets.QPushButton(self.frame_4)
        self.btn_oduncBilgileriGetir_5.setGeometry(QtCore.QRect(510, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_oduncBilgileriGetir_5.setFont(font)
        self.btn_oduncBilgileriGetir_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_oduncBilgileriGetir_5.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_oduncBilgileriGetir_5.setObjectName("btn_oduncBilgileriGetir_5")
        self.label_7.raise_()
        self.label_13.raise_()
        self.label_16.raise_()
        self.frame_4.raise_()
        self.oduncStack.addWidget(self.qw_odunc_iade)
        self.qw_odunc_test = QtWidgets.QWidget()
        self.qw_odunc_test.setObjectName("qw_odunc_test")
        self.frame_7 = QtWidgets.QFrame(self.qw_odunc_test)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1075, 700))
        self.frame_7.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:20px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"QTextEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"\n"
"QTableWidget{\n"
"background:transparent;\n"
"color:white;\n"
"font-color:white;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(260, 20, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 80, 1011, 471))
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        self.kullanici_ogr_no_4 = QtWidgets.QLineEdit(self.frame_7)
        self.kullanici_ogr_no_4.setGeometry(QtCore.QRect(270, 590, 311, 41))
        self.kullanici_ogr_no_4.setText("")
        self.kullanici_ogr_no_4.setMaxLength(24)
        self.kullanici_ogr_no_4.setFrame(True)
        self.kullanici_ogr_no_4.setObjectName("kullanici_ogr_no_4")
        self.btn_oduncAra = QtWidgets.QPushButton(self.frame_7)
        self.btn_oduncAra.setGeometry(QtCore.QRect(630, 580, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_oduncAra.setFont(font)
        self.btn_oduncAra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_oduncAra.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_oduncAra.setObjectName("btn_oduncAra")
        self.btn_oduncListesiGetir = QtWidgets.QPushButton(self.frame_7)
        self.btn_oduncListesiGetir.setGeometry(QtCore.QRect(870, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_oduncListesiGetir.setFont(font)
        self.btn_oduncListesiGetir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_oduncListesiGetir.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_oduncListesiGetir.setObjectName("btn_oduncListesiGetir")
        self.oduncStack.addWidget(self.qw_odunc_test)
        self.mainStack.addWidget(self.qw_odunc)
        self.qw_kullanici = QtWidgets.QWidget()
        self.qw_kullanici.setObjectName("qw_kullanici")
        self.kullaniciStack = QtWidgets.QStackedWidget(self.qw_kullanici)
        self.kullaniciStack.setGeometry(QtCore.QRect(0, 0, 1075, 700))
        self.kullaniciStack.setStyleSheet("")
        self.kullaniciStack.setObjectName("kullaniciStack")
        self.qw_kullanici_kayit = QtWidgets.QWidget()
        self.qw_kullanici_kayit.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"QTextEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.qw_kullanici_kayit.setObjectName("qw_kullanici_kayit")
        self.label_27 = QtWidgets.QLabel(self.qw_kullanici_kayit)
        self.label_27.setGeometry(QtCore.QRect(110, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.qw_kullanici_kayit)
        self.label_28.setGeometry(QtCore.QRect(20, 10, 95, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_28.setObjectName("label_28")
        self.label_32 = QtWidgets.QLabel(self.qw_kullanici_kayit)
        self.label_32.setGeometry(QtCore.QRect(139, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_32.setObjectName("label_32")
        self.kullanici_ogr_no = QtWidgets.QLineEdit(self.qw_kullanici_kayit)
        self.kullanici_ogr_no.setGeometry(QtCore.QRect(270, 180, 448, 41))
        self.kullanici_ogr_no.setText("")
        self.kullanici_ogr_no.setMaxLength(24)
        self.kullanici_ogr_no.setFrame(True)
        self.kullanici_ogr_no.setObjectName("kullanici_ogr_no")
        self.kullanici_soyad = QtWidgets.QLineEdit(self.qw_kullanici_kayit)
        self.kullanici_soyad.setGeometry(QtCore.QRect(270, 300, 448, 41))
        self.kullanici_soyad.setText("")
        self.kullanici_soyad.setMaxLength(24)
        self.kullanici_soyad.setObjectName("kullanici_soyad")
        self.kullanici_adi = QtWidgets.QLineEdit(self.qw_kullanici_kayit)
        self.kullanici_adi.setGeometry(QtCore.QRect(270, 240, 448, 41))
        self.kullanici_adi.setText("")
        self.kullanici_adi.setMaxLength(24)
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.label_14 = QtWidgets.QLabel(self.qw_kullanici_kayit)
        self.label_14.setGeometry(QtCore.QRect(271, 60, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.kullanici_telefon_no = QtWidgets.QLineEdit(self.qw_kullanici_kayit)
        self.kullanici_telefon_no.setGeometry(QtCore.QRect(270, 360, 448, 41))
        self.kullanici_telefon_no.setText("")
        self.kullanici_telefon_no.setMaxLength(24)
        self.kullanici_telefon_no.setObjectName("kullanici_telefon_no")
        self.label_35 = QtWidgets.QLabel(self.qw_kullanici_kayit)
        self.label_35.setGeometry(QtCore.QRect(276, 114, 451, 41))
        self.label_35.setStyleSheet("background:transparent;\n"
"color:silver;\n"
"border:none;\n"
"font-size:15px;")
        self.label_35.setObjectName("label_35")
        self.btn_kullaniciKayit = QtWidgets.QPushButton(self.qw_kullanici_kayit)
        self.btn_kullaniciKayit.setGeometry(QtCore.QRect(390, 490, 225, 64))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.btn_kullaniciKayit.setFont(font)
        self.btn_kullaniciKayit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullaniciKayit.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_kullaniciKayit.setObjectName("btn_kullaniciKayit")
        self.kullanici_mail = QtWidgets.QLineEdit(self.qw_kullanici_kayit)
        self.kullanici_mail.setGeometry(QtCore.QRect(270, 420, 448, 41))
        self.kullanici_mail.setText("")
        self.kullanici_mail.setMaxLength(24)
        self.kullanici_mail.setObjectName("kullanici_mail")
        self.kullaniciStack.addWidget(self.qw_kullanici_kayit)
        self.qw_kullanici_listesi = QtWidgets.QWidget()
        self.qw_kullanici_listesi.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.2);\n"
"}\n"
"QLineEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.04);\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:silver;\n"
"background:transparent\n"
"}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"}\n"
"QTextEdit{\n"
"font-size:25px;;\n"
"color:white;\n"
"border:none;\n"
"background:transparent;\n"
"border-bottom:1px solid white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}\n"
"QTableWidget{\n"
"background:transparent;\n"
"color:white;\n"
"}")
        self.qw_kullanici_listesi.setObjectName("qw_kullanici_listesi")
        self.label_29 = QtWidgets.QLabel(self.qw_kullanici_listesi)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.qw_kullanici_listesi)
        self.label_30.setGeometry(QtCore.QRect(105, 13, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.qw_kullanici_listesi)
        self.label_31.setGeometry(QtCore.QRect(139, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("QLabel{\n"
"color:silver;\n"
"background:transparent;\n"
"}")
        self.label_31.setObjectName("label_31")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.qw_kullanici_listesi)
        self.tableWidget_4.setGeometry(QtCore.QRect(310, 110, 501, 361))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.label_17 = QtWidgets.QLabel(self.qw_kullanici_listesi)
        self.label_17.setGeometry(QtCore.QRect(340, 40, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background:transparent;\n"
"color:rgb(195, 195, 195);\n"
"font-size:36px;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.kullanici_ogr_no_2 = QtWidgets.QLineEdit(self.qw_kullanici_listesi)
        self.kullanici_ogr_no_2.setGeometry(QtCore.QRect(310, 510, 311, 41))
        self.kullanici_ogr_no_2.setText("")
        self.kullanici_ogr_no_2.setMaxLength(24)
        self.kullanici_ogr_no_2.setFrame(True)
        self.kullanici_ogr_no_2.setObjectName("kullanici_ogr_no_2")
        self.btn_kullaniciAra = QtWidgets.QPushButton(self.qw_kullanici_listesi)
        self.btn_kullaniciAra.setGeometry(QtCore.QRect(650, 500, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.btn_kullaniciAra.setFont(font)
        self.btn_kullaniciAra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullaniciAra.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:10px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:rgb(64, 95, 208)\n"
"}")
        self.btn_kullaniciAra.setObjectName("btn_kullaniciAra")
        self.btn_kullaniciBilgileriGetir = QtWidgets.QPushButton(self.qw_kullanici_listesi)
        self.btn_kullaniciBilgileriGetir.setGeometry(QtCore.QRect(840, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_kullaniciBilgileriGetir.setFont(font)
        self.btn_kullaniciBilgileriGetir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullaniciBilgileriGetir.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.btn_kullaniciBilgileriGetir.setObjectName("btn_kullaniciBilgileriGetir")
        self.kullaniciStack.addWidget(self.qw_kullanici_listesi)
        self.mainStack.addWidget(self.qw_kullanici)
        self.qw_hesap = QtWidgets.QWidget()
        self.qw_hesap.setObjectName("qw_hesap")
        self.label_6 = QtWidgets.QLabel(self.qw_hesap)
        self.label_6.setGeometry(QtCore.QRect(210, 20, 381, 131))
        self.label_6.setStyleSheet("color: white;\n"
"font-size:40px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.mainStack.addWidget(self.qw_hesap)
        self.menuStack = QtWidgets.QStackedWidget(self.frame)
        self.menuStack.setGeometry(QtCore.QRect(175, 100, 175, 700))
        self.menuStack.setMinimumSize(QtCore.QSize(175, 700))
        self.menuStack.setMaximumSize(QtCore.QSize(1075, 700))
        self.menuStack.setStyleSheet("QWidget{\n"
"background:transparent\n"
"}\n"
"")
        self.menuStack.setObjectName("menuStack")
        self.menu_kitap = QtWidgets.QWidget()
        self.menu_kitap.setObjectName("menu_kitap")
        self.btn_kitap_kayit = QtWidgets.QPushButton(self.menu_kitap)
        self.btn_kitap_kayit.setGeometry(QtCore.QRect(0, 170, 175, 57))
        self.btn_kitap_kayit.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kitap_kayit.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kitap_kayit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitap_kayit.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_kitap_kayit.setObjectName("btn_kitap_kayit")
        self.btn_kitap_duzenle = QtWidgets.QPushButton(self.menu_kitap)
        self.btn_kitap_duzenle.setGeometry(QtCore.QRect(0, 227, 175, 57))
        self.btn_kitap_duzenle.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kitap_duzenle.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kitap_duzenle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitap_duzenle.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_kitap_duzenle.setObjectName("btn_kitap_duzenle")
        self.btn_kitap_test = QtWidgets.QPushButton(self.menu_kitap)
        self.btn_kitap_test.setGeometry(QtCore.QRect(0, 284, 175, 56))
        self.btn_kitap_test.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kitap_test.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kitap_test.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kitap_test.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_kitap_test.setObjectName("btn_kitap_test")
        self.menuStack.addWidget(self.menu_kitap)
        self.menu_odunc = QtWidgets.QWidget()
        self.menu_odunc.setObjectName("menu_odunc")
        self.btn_odunc_test = QtWidgets.QPushButton(self.menu_odunc)
        self.btn_odunc_test.setGeometry(QtCore.QRect(0, 453, 175, 57))
        self.btn_odunc_test.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_odunc_test.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_odunc_test.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_odunc_test.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_odunc_test.setObjectName("btn_odunc_test")
        self.btn_odunc_iade = QtWidgets.QPushButton(self.menu_odunc)
        self.btn_odunc_iade.setGeometry(QtCore.QRect(0, 397, 175, 56))
        self.btn_odunc_iade.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_odunc_iade.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_odunc_iade.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_odunc_iade.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_odunc_iade.setObjectName("btn_odunc_iade")
        self.btn_odunc_ver = QtWidgets.QPushButton(self.menu_odunc)
        self.btn_odunc_ver.setGeometry(QtCore.QRect(0, 340, 175, 57))
        self.btn_odunc_ver.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_odunc_ver.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_odunc_ver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_odunc_ver.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_odunc_ver.setObjectName("btn_odunc_ver")
        self.menuStack.addWidget(self.menu_odunc)
        self.menu_kullanici = QtWidgets.QWidget()
        self.menu_kullanici.setObjectName("menu_kullanici")
        self.btn_kullanici_kayit = QtWidgets.QPushButton(self.menu_kullanici)
        self.btn_kullanici_kayit.setGeometry(QtCore.QRect(0, 510, 175, 85))
        self.btn_kullanici_kayit.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kullanici_kayit.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kullanici_kayit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullanici_kayit.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_kullanici_kayit.setObjectName("btn_kullanici_kayit")
        self.btn_kullanici_liste = QtWidgets.QPushButton(self.menu_kullanici)
        self.btn_kullanici_liste.setGeometry(QtCore.QRect(0, 595, 175, 85))
        self.btn_kullanici_liste.setMinimumSize(QtCore.QSize(175, 0))
        self.btn_kullanici_liste.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btn_kullanici_liste.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kullanici_liste.setStyleSheet("QPushButton{\n"
"background:rgba(45,54,76,0.99);\n"
"border:none;\n"
"color:silver;\n"
"font-size:18px;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(35,43,62,0.99);\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid rgb(38,46,65)\n"
"}\n"
"")
        self.btn_kullanici_liste.setObjectName("btn_kullanici_liste")
        self.menuStack.addWidget(self.menu_kullanici)
        self.gorevCubugu.raise_()
        self.btn_kitap.raise_()
        self.btn_odunc.raise_()
        self.btn_kullanici.raise_()
        self.btn_profil.raise_()
        self.mainStack.raise_()
        self.menuStack.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1250, 40))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.45);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.50);\n"
"}\n"
"\n"
"QPushButton{\n"
"color:silver;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(14, 5, 21, 31))
        self.label_3.setStyleSheet("background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(41, 11, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:silver;\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(1211, 0, 41, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"color:silver;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:red;\n"
"color:white\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_2)
        self.btn_minimize.setGeometry(QtCore.QRect(1170, 0, 41, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.btn_minimize.setFont(font)
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"background:rgba(0, 0, 0,0.15);\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:rgba(0, 0, 0,0.6)\n"
"}")
        self.btn_minimize.setObjectName("btn_minimize")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(0)
        self.kitapStack.setCurrentIndex(2)
        self.combo_edit_kitap.setCurrentIndex(-1)
        self.oduncStack.setCurrentIndex(0)
        self.combo_odunc_kitap.setCurrentIndex(-1)
        self.combo_odunc_kullanici.setCurrentIndex(-1)
        self.combo_odunc_bilgi.setCurrentIndex(-1)
        self.kullaniciStack.setCurrentIndex(1)
        self.menuStack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kütüphane Sistemi"))
        self.btn_profil.setText(_translate("MainWindow", "PROFİL"))
        self.label_telefon_no.setText(_translate("MainWindow", "Telefon Numarası"))
        self.label_username.setText(_translate("MainWindow", "KULLANICI ADI"))
        self.btn_kitap.setText(_translate("MainWindow", "KİTAP\n"
"İŞLEMLERİ"))
        self.btn_odunc.setText(_translate("MainWindow", "ÖDÜNÇ\n"
"İŞLEMLERİ"))
        self.btn_kullanici.setText(_translate("MainWindow", "KULLANICI\n"
"İŞLEMLERİ"))
        self.profil_ad.setPlaceholderText(_translate("MainWindow", "Ad"))
        self.profil_mail.setPlaceholderText(_translate("MainWindow", "Mail Adresi"))
        self.profil_kullanici_adi.setPlaceholderText(_translate("MainWindow", "Kullanıcı Adı"))
        self.profil_telefon.setPlaceholderText(_translate("MainWindow", "Telefon"))
        self.profil_parola.setPlaceholderText(_translate("MainWindow", "Parola"))
        self.profil_soyad.setPlaceholderText(_translate("MainWindow", "Soyad"))
        self.profil_parola_yeni.setPlaceholderText(_translate("MainWindow", "Parola"))
        self.btn_profilParola.setText(_translate("MainWindow", "Parola Değiştir"))
        self.btn_profilParola.setShortcut(_translate("MainWindow", "Return"))
        self.label_26.setText(_translate("MainWindow", "Personel Bilgileri"))
        self.label_22.setText(_translate("MainWindow", " ⇢"))
        self.label_23.setText(_translate("MainWindow", "Profil"))
        self.label_18.setText(_translate("MainWindow", "Kitap İşlemleri"))
        self.label_19.setText(_translate("MainWindow", " ⇢"))
        self.label_24.setText(_translate("MainWindow", "Kitap Ekle"))
        self.kitap_ekle_yazar.setPlaceholderText(_translate("MainWindow", "Yazar Adı"))
        self.kitap_ekle_adi.setPlaceholderText(_translate("MainWindow", "Kitap Adı"))
        self.btn_kitapEkle.setText(_translate("MainWindow", "Kitap Ekle"))
        self.btn_kitapEkle.setShortcut(_translate("MainWindow", "Return"))
        self.label_11.setText(_translate("MainWindow", "KİTAP EKLEME İŞLEMİ"))
        self.label_33.setText(_translate("MainWindow", "Kitap eklemek için aşağıdaki alanları eksiksiz bir şekilde doldurup \n"
"\'Kitap Ekle\' Butonuna basınız."))
        self.kitap_ekle_sayfa.setPlaceholderText(_translate("MainWindow", "Sayfa Sayısı"))
        self.kitap_ekle_basim.setPlaceholderText(_translate("MainWindow", "Basım Tarihi"))
        self.label_40.setText(_translate("MainWindow", "Kitap Resmi"))
        self.kitap_ekle_yayinevi.setPlaceholderText(_translate("MainWindow", "Yayınevi"))
        self.kitap_ekle_tur.setPlaceholderText(_translate("MainWindow", "Kitap Türü"))
        self.label_20.setText(_translate("MainWindow", " ⇢"))
        self.label_21.setText(_translate("MainWindow", "Kitap İşlemleri"))
        self.label_25.setText(_translate("MainWindow", "Kitap Düzenle"))
        self.kitap_edit_ad.setPlaceholderText(_translate("MainWindow", "Kitap Adı"))
        self.kitap_edit_sayfa.setPlaceholderText(_translate("MainWindow", "Sayfa Sayısı"))
        self.label_9.setText(_translate("MainWindow", "Kitap düzenlemek için kitap seç bölümünden kitap seçip \'BİLGİLERİ GETİR\' e bastıktan sonra, \n"
"kitap bilgileri üzerinde değişiklik yapıp \'Kitap Düzenle\' butonuna basınız."))
        self.kitap_edit_yayinevi.setPlaceholderText(_translate("MainWindow", "Yayınevi"))
        self.kitap_edit_basim.setPlaceholderText(_translate("MainWindow", "Basım Tarihi"))
        self.btn_kitapSil.setText(_translate("MainWindow", "Kitap Sil"))
        self.btn_kitapSil.setShortcut(_translate("MainWindow", "Return"))
        self.kitap_edit_tur.setPlaceholderText(_translate("MainWindow", "Kitap Türü"))
        self.btn_kitapDuzenle.setText(_translate("MainWindow", "Kitap Düzenle"))
        self.btn_kitapDuzenle.setShortcut(_translate("MainWindow", "Return"))
        self.btn_kitapBilgileriGetir.setText(_translate("MainWindow", "BİLGİLERİ GETİR"))
        self.btn_kitapBilgileriGetir.setShortcut(_translate("MainWindow", "Return"))
        self.label_12.setText(_translate("MainWindow", "KİTAP DÜZENLEME İŞLEMİ"))
        self.kitap_edit_yazar.setPlaceholderText(_translate("MainWindow", "Yazar Adı"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Barkod No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yazar Adı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yayınevi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tür"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sayfa Sayısı"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Basım Tarihi"))
        self.btn_kullaniciAra_2.setText(_translate("MainWindow", "Ara"))
        self.btn_kullaniciAra_2.setShortcut(_translate("MainWindow", "Return"))
        self.kullanici_ogr_no_3.setPlaceholderText(_translate("MainWindow", "Kitap Adı"))
        self.btn_kitapBilgileriGetir_2.setText(_translate("MainWindow", "Kitap Bilgisi"))
        self.btn_kitapBilgileriGetir_2.setShortcut(_translate("MainWindow", "Return"))
        self.label_4.setText(_translate("MainWindow", "Ödünç İşlemleri"))
        self.label_10.setText(_translate("MainWindow", " ⇢"))
        self.label_15.setText(_translate("MainWindow", "Ödünç Ver"))
        self.btn_oduncVer.setText(_translate("MainWindow", "Ödünç Ver"))
        self.btn_oduncVer.setShortcut(_translate("MainWindow", "Return"))
        self.label.setText(_translate("MainWindow", "KİTAP ÖDÜNÇ VER"))
        self.odunc_ver_barkod.setPlaceholderText(_translate("MainWindow", "Kitap Barkod No"))
        self.btn_kitapBilgileriGetir_3.setText(_translate("MainWindow", "KİTAP BİLGİSİ"))
        self.btn_kitapBilgileriGetir_3.setShortcut(_translate("MainWindow", "Return"))
        self.odunc_ver_kitap.setPlaceholderText(_translate("MainWindow", "Kitap Adı"))
        self.odunc_ver_yazar.setPlaceholderText(_translate("MainWindow", "Yazar Adı"))
        self.btn_kitapBilgileriGetir_4.setText(_translate("MainWindow", "KULLANICI BİLGİSİ"))
        self.btn_kitapBilgileriGetir_4.setShortcut(_translate("MainWindow", "Return"))
        self.odunc_ver_adsoyad.setPlaceholderText(_translate("MainWindow", "Ad Soyad"))
        self.odunc_ver_ogrno.setPlaceholderText(_translate("MainWindow", "Öğrenci Numarası"))
        self.odunc_ver_telefon.setPlaceholderText(_translate("MainWindow", "Telefon Numarası"))
        self.odunc_ver_yayinevi.setPlaceholderText(_translate("MainWindow", "Yayınevi"))
        self.odunc_ver_tarih.setPlaceholderText(_translate("MainWindow", "Alınma Tarihi"))
        self.label_13.setText(_translate("MainWindow", " ⇢"))
        self.label_7.setText(_translate("MainWindow", "Ödünç İşlemleri"))
        self.label_16.setText(_translate("MainWindow", "Ödünç İade"))
        self.btn_oduncIade.setText(_translate("MainWindow", "Kitap İade"))
        self.btn_oduncIade.setShortcut(_translate("MainWindow", "Return"))
        self.odunc_iade_yazar.setPlaceholderText(_translate("MainWindow", "Yazar Adı"))
        self.odunc_iade_telefon.setPlaceholderText(_translate("MainWindow", "Telefon Numarası"))
        self.odunc_iade_tarih.setPlaceholderText(_translate("MainWindow", "Teslim Tarihi"))
        self.odunc_iade_barkod.setPlaceholderText(_translate("MainWindow", "Kitap Barkod No"))
        self.odunc_iade_ogrno.setPlaceholderText(_translate("MainWindow", "Öğrenci Numarası"))
        self.odunc_iade_adsoyad.setPlaceholderText(_translate("MainWindow", "Ad Soyad"))
        self.odunc_iade_yayinevi.setPlaceholderText(_translate("MainWindow", "Yayınevi"))
        self.label_5.setText(_translate("MainWindow", "KİTAP ÖDÜNÇ İADE"))
        self.odunc_iade_kitap.setPlaceholderText(_translate("MainWindow", "Kitap Adı"))
        self.btn_oduncBilgileriGetir_5.setText(_translate("MainWindow", "ÖDÜNÇ BİLGİSİ"))
        self.btn_oduncBilgileriGetir_5.setShortcut(_translate("MainWindow", "Return"))
        self.label_8.setText(_translate("MainWindow", "ÖDÜNÇ LİSTESİ"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ödünç İd"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kitap Barkod"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yazar Adı"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yayınevi"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Öğrenci Numarası"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ad Soyad"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Telefon"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Alınma Tarihi"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Teslim Tarihi"))
        self.kullanici_ogr_no_4.setPlaceholderText(_translate("MainWindow", "Öğrenci Numarası"))
        self.btn_oduncAra.setText(_translate("MainWindow", "Ara"))
        self.btn_oduncAra.setShortcut(_translate("MainWindow", "Return"))
        self.btn_oduncListesiGetir.setText(_translate("MainWindow", "Ödünç Listesi"))
        self.btn_oduncListesiGetir.setShortcut(_translate("MainWindow", "Return"))
        self.label_27.setText(_translate("MainWindow", " ⇢"))
        self.label_28.setText(_translate("MainWindow", "Kullanıcı İşlemleri"))
        self.label_32.setText(_translate("MainWindow", "Kullanıcı Kayıt"))
        self.kullanici_ogr_no.setPlaceholderText(_translate("MainWindow", "Öğrenci Numarası"))
        self.kullanici_soyad.setPlaceholderText(_translate("MainWindow", "Soyad"))
        self.kullanici_adi.setPlaceholderText(_translate("MainWindow", "Ad"))
        self.label_14.setText(_translate("MainWindow", "Yeni Kullanıcı Kaydı"))
        self.kullanici_telefon_no.setPlaceholderText(_translate("MainWindow", "Telefon Numarası"))
        self.label_35.setText(_translate("MainWindow", "Yeni kullanıcı eklemek için aşağıdaki alanları eksiksiz bir şekilde doldurup\n"
"\'Kaydet\' Butonuna basınız."))
        self.btn_kullaniciKayit.setText(_translate("MainWindow", "Kaydet"))
        self.btn_kullaniciKayit.setShortcut(_translate("MainWindow", "Return"))
        self.kullanici_mail.setPlaceholderText(_translate("MainWindow", "Mail Adresi"))
        self.label_29.setText(_translate("MainWindow", "Kullanıcı İşlemleri"))
        self.label_30.setText(_translate("MainWindow", " ⇢"))
        self.label_31.setText(_translate("MainWindow", "Kullanıcı Listesi"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kullanıcı İd"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Öğrenci No"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Soyad"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Telefon No"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mail Adresi"))
        self.label_17.setText(_translate("MainWindow", "KULLANICI LİSTESİ"))
        self.kullanici_ogr_no_2.setPlaceholderText(_translate("MainWindow", "Öğrenci Numarası"))
        self.btn_kullaniciAra.setText(_translate("MainWindow", "Ara"))
        self.btn_kullaniciAra.setShortcut(_translate("MainWindow", "Return"))
        self.btn_kullaniciBilgileriGetir.setText(_translate("MainWindow", "Kullanıcı Bilgisi"))
        self.btn_kullaniciBilgileriGetir.setShortcut(_translate("MainWindow", "Return"))
        self.label_6.setText(_translate("MainWindow", "HESAP AYARLARI"))
        self.btn_kitap_kayit.setText(_translate("MainWindow", "KİTAP EKLE"))
        self.btn_kitap_duzenle.setText(_translate("MainWindow", "KİTAP DÜZENLE"))
        self.btn_kitap_test.setText(_translate("MainWindow", "KİTAP LİSTESİ"))
        self.btn_odunc_test.setText(_translate("MainWindow", "ÖDÜNÇ LİSTESİ"))
        self.btn_odunc_iade.setText(_translate("MainWindow", "ÖDÜNÇ İADE"))
        self.btn_odunc_ver.setText(_translate("MainWindow", "ÖDÜNÇ VER"))
        self.btn_kullanici_kayit.setText(_translate("MainWindow", "KULLANICI KAYIT"))
        self.btn_kullanici_liste.setText(_translate("MainWindow", "KULLANICI LİSTESİ"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/images/beulogo_login.png\" width=\"21\" height=\"30\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Kütüphane Sistemi"))
        self.btn_close.setText(_translate("MainWindow", "✕"))
        self.btn_minimize.setText(_translate("MainWindow", "_"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
